<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTlnJ6DQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTlnJ6DQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTlnJ6DQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTlnJ6DQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTlnJ6DQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'TlnJ6DQ',
    'container.build_id' => '96375f66',
    'container.build_time' => 1664443698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTlnJ6DQ');
